### ISSUE TITLE
Feature request: Adding a tag item into departure list

### ISSUE THREAD

**Issue by bostjanlaba** [KingfuChan/RDF#6]
Is there any chance of adding a tag item with some symbol being shown while a callsign is transmitting? 

So for example when you have flightplans on departure list, one callsign calls you on frequency and since RDF already knows all the data, it would display some symbol like [!] in the column next to the callsign in the departure (or any other) list. 

No need to erase the symbol until next callsign calls. So basically we have a marking of the last callsign calling, but instead just written like in AFV or TrackAudio, it is actually marked on the lists inside Euroscope.

Thanks.

**Comment by KingfuChan** [comment]
try the pre-release v1.4.0

**Comment by bostjanlaba** [comment]
Tried it, put it on departure list but it does not seem to work. No indicator is shown during TX from TrackAudio. Circles around aircraft are displayed properly. Only problem with circles is that if pilot disconnects during transmission, circle stays forever. Perhaps some command like .rdf reset would be good to be available for similar issues.

**Comment by bostjanlaba** [comment]
Just retried and now it works regarding the indicator in the departure list :)

**Comment by KingfuChan** [comment]
Happy to know the indicator working fine!



> Only problem with circles is that if pilot disconnects during transmission, circle stays forever. Perhaps some command like .rdf reset would be good to be available for similar issues.

You may try `.rdf reload`, it should work.
